######################################################################
# Automatically generated by qmake (2.01a) Sun Aug 17 16:07:49 2014
######################################################################

TEMPLATE = app
CONFIG += qt

INCLUDEPATH += include
OBJECTS_DIR = build
MOC_DIR = build
DESTDIR = bin

HEADERS += include/MainWindow.h
HEADERS += include/Looper.h

SOURCES += src/main.cpp
SOURCES += src/MainWindow.cpp
SOURCES += src/Looper.cpp

LIBS += -lsndfile -lasound
